name: localize
description: Translate service

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.2
  provider: ^4.3.3
  shared_preferences: ^0.5.12+4
  #  path: ^1.7.0
  #  path_provider: ^1.6.27
  #  sqflite: ^1.3.2+2
  #  flutter_secure_storage: ^3.3.5
  #  biometric_storage: ^1.1.0+1
  logger: ^0.9.4

  # Images
  rive: ^0.6.4

  # Use with the Cupertino Icons class for iOS style icons.
  cupertino_icons: ^1.0.2

#  country_icons: ^1.1.1
#  flag: ^3.0.5
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/rive/
    - assets/images/

  #  fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages